const Actions = {
  ADD_LIST: 'ADD_LIST',
  DELETE_LIST: 'DELETE_LIST',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  TOGGLE_ITEM: 'TOGGLE_ITEM',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',
  UPDATE_ITEM: 'UPDATE_ITEM',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
};

export default Actions;
